[tool.black]
line-length = 79
target-version = ['py35']

[tool.mypy]
python_version = "3.8"
exclude = [
    '/interfaces/',
    'interfaces\.py$',
]

[[tool.mypy.overrides]]
module = "ampoule.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "apt_inst"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "apt_pkg"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "artifactory"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "bleach_allowlist"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "breezy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "brzbuildrecipe.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "cryptography.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "debian.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "defusedxml.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "dohq_artifactory.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "feedparser"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "fixtures"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "gpgme"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "iso8601"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "launchpadlib.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "lazr.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "lpbuildd.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "oops"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "oops_amqp"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "oops_datedir_repo.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "packaging"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pgbouncer.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pymacaroons"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pystache"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "requests_toolbelt.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "responses"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "selenium.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "soupmatchers"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "soupsieve"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "storm.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "subunit"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "swiftclient"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "talisker.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "testscenarios.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "testtools.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "transaction"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "treq"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "twisted.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "txfixtures.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "webob.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "webtest"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "wsgi_intercept"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "wsgiproxy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "zope.*"
ignore_missing_imports = true

